services:
  api:
    container_name: mpit.server
    image: mpitserver
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      #- ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    build:
      context: .
      dockerfile: ./mpit/Dockerfile
    volumes:
      - ./ssl:/app/ssl
      - ./:/app
    networks:
      - mpit
    depends_on:
      - user_db

  user_db:
    container_name: mpit.user-db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mpitdb
      POSTGRES_USER: mpit124
      POSTGRES_PASSWORD: mpit124
    networks:
      - mpit
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  mpit:
    driver: bridge

volumes:
  postgres-data: